AWSTemplateFormatVersion: '2010-09-09'
Description: "Full CI/CD setup for Vite React Quiz App with EC2, CodeBuild, CodeDeploy, CodePipeline"

Parameters:
  GitHubToken:
    Type: String
    Description: GitHub Personal Access Token for CodePipeline
    NoEcho: true

  EC2KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access

  LatestAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2
    Description: Latest Amazon Linux 2 AMI

Resources:

  ### S3 Bucket for CodePipeline Artifacts ###
  QuizAppPipelineArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      Tags:
        - Key: Name
          Value: !Sub '${AWS::StackName}-pipeline-artifacts'

  ### VPC & Networking ###
  QuizAppVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: QuizAppVPC

  QuizAppInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: QuizAppIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref QuizAppVPC
      InternetGatewayId: !Ref QuizAppInternetGateway

  QuizAppPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QuizAppVPC
      CidrBlock: 10.0.1.0/24
      MapPublicIpOnLaunch: true
      AvailabilityZone: !Select [0, !GetAZs 'ap-south-1']
      Tags:
        - Key: Name
          Value: QuizAppPublicSubnet

  QuizAppRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref QuizAppVPC
      Tags:
        - Key: Name
          Value: QuizAppRouteTable

  QuizAppRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref QuizAppRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref QuizAppInternetGateway

  QuizAppSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref QuizAppPublicSubnet
      RouteTableId: !Ref QuizAppRouteTable

  ### Security Group ###
  QuizAppSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow HTTP traffic + SSH
      VpcId: !Ref QuizAppVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  ### IAM Roles ###
  QuizAppEC2Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Tags:
        - Key: Name
          Value: QuizAppEC2Role

  QuizAppInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref QuizAppEC2Role

  QuizAppCodeDeployServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
      Tags:
        - Key: Name
          Value: QuizAppCodeDeployRole

  QuizAppCodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildArtifactsAccess
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetBucketAcl
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${QuizAppPipelineArtifactsBucket}/*"
                  - !Sub "arn:aws:s3:::${QuizAppPipelineArtifactsBucket}"
        - PolicyName: CodeBuildCloudWatchLogs
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "arn:aws:logs:*:*:*"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
      Tags:
        - Key: Name
          Value: QuizAppCodeBuildRole

  QuizAppCodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodePipelineServicePolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:GetBucketAcl
                  - s3:ListBucket
                Resource:
                  - !Sub "arn:aws:s3:::${QuizAppPipelineArtifactsBucket}"
                  - !Sub "arn:aws:s3:::${QuizAppPipelineArtifactsBucket}/*"
              - Effect: Allow
                Action:
                  - codebuild:StartBuild
                  - codebuild:BatchGetBuilds
                Resource: !GetAtt QuizAppCodeBuildProject.Arn
              - Effect: Allow
                Action:
                  - codedeploy:CreateDeployment
                  - codedeploy:GetDeployment
                  - codedeploy:GetDeploymentConfig
                  - codedeploy:RegisterApplicationRevision
                  - codedeploy:GetApplicationRevision
                Resource: "*"
      Tags:
        - Key: Name
          Value: QuizAppCodePipelineRole

  ### EC2 Instance ###
  QuizAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: t2.micro
      SubnetId: !Ref QuizAppPublicSubnet
      SecurityGroupIds:
        - !Ref QuizAppSecurityGroup
      IamInstanceProfile: !Ref QuizAppInstanceProfile
      KeyName: !Ref EC2KeyName
      Tags:
        - Key: Name
          Value: QuizAppEC2
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          amazon-linux-extras enable nginx1
          yum install -y nginx git ruby wget
          systemctl enable nginx
          systemctl start nginx
          
          curl -sL https://rpm.nodesource.com/setup_18.x | bash -
          yum install -y nodejs
          npm install -g serve

          # Install CodeDeploy agent
          cd /tmp
          wget https://aws-codedeploy-${AWS::Region}.s3.${AWS::Region}.amazonaws.com/latest/install
          chmod +x ./install
          ./install auto
          systemctl enable codedeploy-agent
          systemctl start codedeploy-agent

  ### CodeDeploy ###
  QuizAppCodeDeployApp:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName: QuizAppCodeDeploy
      ComputePlatform: Server

  QuizAppDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName: !Ref QuizAppCodeDeployApp
      DeploymentGroupName: QuizAppDeploymentGroup
      ServiceRoleArn: !GetAtt QuizAppCodeDeployServiceRole.Arn
      DeploymentConfigName: CodeDeployDefault.AllAtOnce
      Ec2TagFilters:
        - Key: Name
          Value: QuizAppEC2
          Type: KEY_AND_VALUE

  ### CodeBuild ###
  QuizAppCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: QuizAppCodeBuild
      Source:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt QuizAppCodeBuildServiceRole.Arn
      Artifacts:
        Type: CODEPIPELINE

  ### CodePipeline ###
  QuizAppPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: QuizAppPipeline
      RoleArn: !GetAtt QuizAppCodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref QuizAppPipelineArtifactsBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHub_Source
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: Ananya636
                Repo: CI-CD-Pipeline-for-AWS-Application
                Branch: main
                OAuthToken: !Ref GitHubToken
        - Name: Build
          Actions:
            - Name: CodeBuild
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref QuizAppCodeBuildProject
        - Name: Deploy
          Actions:
            - Name: CodeDeploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CodeDeploy
                Version: 1
              InputArtifacts:
                - Name: BuildOutput
              Configuration:
                ApplicationName: !Ref QuizAppCodeDeployApp
                DeploymentGroupName: !Ref QuizAppDeploymentGroup

Outputs:
  InstancePublicIP:
    Description: Public IP of EC2 instance
    Value: !GetAtt QuizAppInstance.PublicIp
  CodePipelineName:
    Description: Name of the CodePipeline
    Value: !Ref QuizAppPipeline

